language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "2.7.10"

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt

script:
  - python manage.py test

env:
  - APP_CONFIG="project.config.TestingConfig"

after_success:
  - codecov
