language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "2.7.10"

install:
  - pip install -r requirements.txt

script:
  - python manage.py runserver

env:
  - APP_CONFIG="project.config.DevelopmentConfig"
