"""empty message

Revision ID: 1bba9aa8e3
Revises: None
Create Date: 2015-11-14 15:52:56.405573

"""

# revision identifiers, used by Alembic.
revision = '1bba9aa8e3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
